[package]
name = "service_utils_rs"
version = "0.3.1"
edition = "2021"
authors = ["code-serenade <arthas.you@163.com>"]
description = "A brief description of your crate"
repository = "https://github.com/code-serenade/service_utils_rs"
homepage = "https://github.com/code-serenade/service_utils_rs"
license = "MIT"
documentation = "https://docs.rs/service_utils_rs"

[dependencies]
byteorder = "1.5.0"
bytes = "1.10.0"
chrono = "0.4.38"
config = "0.15.8"
futures = "0.3.30"
futures-util = "0.3.30"
jsonwebtoken = { version = "9.3.1", optional = true }
serde = { version = "1.0.204", features = ["derive"] }
thiserror = "2.0.11"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.26", optional = true }
reqwest = { version = "0.12.12", features = ["json"] }
url = "2.2"
serde_json = "1.0.138"
surrealdb = { version = "2", optional = true }
axum = { version = "0.8.1", features = ["macros"] }


[features]
jwt = ["jsonwebtoken"]
websocket = ["tokio-tungstenite"]
db = ["surrealdb"]

full = ["jwt", "websocket", "db"]

[package.metadata.docs.rs]
features = ["jwt", "websocket", "db"]
